#########################################################################
#									#
# File ID: ./.travis.yml						#
# Author: Copyright (C) 2019, 2020  Mark Grant				#
#									#
# Released under the GPLv3 only.					#
# SPDX-License-Identifier: GPL-3.0					#
#									#
# Configuration file for Travis CI build tests.				#
#									#
#########################################################################

#########################################################################
#									#
# Changelog								#
#									#
# Date		Author	Version	Description				#
#									#
# 30/10/2019	MG	1.0.1	Initial release.                        #
# 06/11/2019    MG      1.0.2   Bionic is now the minimum distribution  #
#                               due to dependencies built on LaunchPad. #
# 08/06/2020    MG      1.0.3   Remove install of unused program dia.   #
# 16/09/2020    MG      1.0.4   Use new libmgec2-dev package.           #
#									#
#########################################################################


language: c

dist:
    - bionic

before_install:
    - sudo add-apt-repository ppa:m-grant-prg/utils -y
    - sudo apt-get update
    - sudo apt-get install -y autoconf-archive libtool-bin
    - sudo apt-get install -y doxygen graphviz
    - sudo apt-get install -y libmgec2 libmgec2-dev txt2man txt2manwrap

script:
    - autoreconf -if .
    - ./configure --enable-silent-rules=yes
    - make --quiet
    - make --quiet check
    - make --quiet distcheck

after_failure:
    - cat */_build/sub/src/prg/c/src/*/*.log

