#########################################################################
#									#
# File ID: ./.github/workflows/publish-doxygen-gh-pages.yml		#
# Author: Copyright (C) 2022  Mark Grant				#
#									#
# Released under the GPLv3 only.					#
# SPDX-License-Identifier: GPL-3.0-only					#
#									#
# Purpose:								#
# Configuration file for GitHub Actions publication of Doxygen          #
# documentation to Github Pages. Only runs on published release event.  #
#									#
#########################################################################

#########################################################################
#									#
# Changelog								#
#									#
# Date		Author	Version	Description				#
#									#
# 26/07/2022	MG	1.0.1	Initial release.                        #
# 03/11/2022    MG      1.0.2   Use special final libmgec2 which is     #
#                               named libmgec3.                         #
#									#
#########################################################################


name: Publish Doxygen Documentation to Github Pages

on:
  release:
    types: [released]

jobs:
  publish-doxygen:
    runs-on: ubuntu-latest

    steps:
      # Check-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Get all incl tags, needed for git-enhanced AC_INIT
          ref: ${{ github.event.release.tag_name }}

      - name: Add the extra PPA
        run: sudo add-apt-repository ppa:m-grant-prg/utils -y

      - name: Update the package list
        run: sudo apt-get update

      - name: Add the extra PPA packages
        run: |
          sudo apt-get install -y autoconf-archive libtool-bin
          sudo apt-get install -y doxygen graphviz
          sudo apt-get install -y libmgec3 libmgec3-dev txt2man txt2manwrap

      - name: Autoreconf
        run: autoreconf -if .

      - name: Configure
        run: ./configure --enable-silent-rules=yes

      - name: Make doxygen
        run: make doxygen

      - name: Create .nojekyll
        run: touch docs/doxygen/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          branch: gh-pages
          folder: docs/doxygen

